import AppKit

/// Official provider desktop-app icons (issue #103, Tim directive
/// 2026-07-21): Claude accounts show Claude.app's icon; Codex accounts show
/// ChatGPT.app's icon (Tim's explicit choice for the Codex mark). Grok shows
/// the official Grok mark rendered on the brand-black tile
/// (scripts/generate-grok-provider-icon.swift).
///
/// The Claude/Codex PNGs under `Resources/` are extracted from the installed
/// apps' own `.icns` (provenance in the issue #103 PR); the Grok PNGs are
/// generated by the committed script. All the artwork carries the macOS
/// squircle shape with transparent margins, so callers render it as-is — no
/// chip backing, no extra masking.
public enum ProviderIcons {
    /// Pixel sizes bundled per provider (`<baseName>-<px>.png`). 32/64/128
    /// covers the UI's 13-20 pt slots at 1x and 2x with headroom.
    public static let pixelSizes: [Int] = [32, 64, 128]

    /// Providers whose artwork actually ships in the resource bundle. The
    /// bundle-shape tripwires iterate THIS, not `allCases`, so a provider
    /// that claims a base name must ship every declared pixel size — while a
    /// provider that ships none is a stated fact, not a broken test. Every
    /// provider ships artwork today; keep the filter so a future one can
    /// launch icon-less without breaking the tripwires.
    public static var bundledProviders: [DeckProvider] {
        DeckProvider.allCases.filter { resourceBaseName(for: $0) != nil }
    }

    /// Bundled resource base name for a provider's icon, or nil for a
    /// provider whose artwork ModelDeck does not ship. Grok's PNGs are not
    /// an extracted `.icns` like the other two (no installed Grok desktop
    /// app to take one from) — they render the official Grok mark, generated
    /// reproducibly by scripts/generate-grok-provider-icon.swift.
    public static func resourceBaseName(for provider: DeckProvider) -> String? {
        switch provider {
        case .claude: return "provider-claude"
        case .codex: return "provider-codex"
        case .grok: return "provider-grok"
        }
    }

    /// Multi-representation image (one rep per bundled pixel size, sharing a
    /// single point size) so AppKit picks the sharpest rep for the drawn
    /// size, retina included. `nil` only if the bundle is missing a PNG.
    public static func image(for provider: DeckProvider) -> NSImage? {
        switch provider {
        case .claude: return claudeImage
        case .codex: return codexImage
        case .grok: return grokImage
        }
    }

    // NSImage is assembled once and only ever drawn afterwards; cache one
    // per provider (same pattern as the shared CGPaths the vector marks used).
    private static let claudeImage = loadImage(for: .claude)
    private static let codexImage = loadImage(for: .codex)
    private static let grokImage = loadImage(for: .grok)

    private static func loadImage(for provider: DeckProvider) -> NSImage? {
        // Issue #158: NEVER Bundle.module here — its plain-`swift build`
        // accessor only checks the app root and a baked builder path, and
        // traps when both miss (the v0.3.3/v0.3.4 field crash). The
        // explicit resolver checks Contents/Resources first and degrades
        // to nil (callers keep their fallback glyphs) instead of trapping.
        guard let bundle = CoreResourceBundle.bundle,
              let base = resourceBaseName(for: provider) else { return nil }
        // Shared point size; drawing scales it anyway. 16 keeps 1 pt = 2-8 px.
        let pointSize = NSSize(width: 16, height: 16)
        let image = NSImage(size: pointSize)
        for pixels in pixelSizes {
            guard let url = bundle.url(forResource: "\(base)-\(pixels)", withExtension: "png"),
                  let data = try? Data(contentsOf: url),
                  let rep = NSBitmapImageRep(data: data) else {
                return nil
            }
            rep.size = pointSize
            image.addRepresentation(rep)
        }
        return image
    }
}
