import AppKit
import Foundation
import ModelDeckMacCore

// Issue #396: the one step of the in-app credential repair that leaves the
// app. The URL is the PROVIDER's own authorize page, generated by
// CLIProxyAPI — ModelDeck neither builds it nor reads what comes back; the
// proxy owns the callback and writes its own auth file (#398).
//
// The live half of the `BrowserOpening` seam lives in the app target only,
// so Core tests drive the whole flow without a browser ever appearing.
struct WorkspaceBrowserOpener: BrowserOpening {
    func open(_ url: URL) {
        NSWorkspace.shared.open(url)
    }
}
